In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, TimeoutException
import time
import pandas as pd

In [2]:
MAIN_URL = 'https://med.over.net/forum'

driver = webdriver.Chrome()
driver.get(MAIN_URL)
time.sleep(2)

In [30]:
# Main forum page lists different forums. Extract links to all the forums. Also take care of possible ads showing prior to content loading.
'''
[
  {
    "category": "Duševno zdravje in odnosi",
    "forum": "Družina",
    "link": "https://med.over.net/forum/kategorija/dusevno-zdravje-in-odnosi/druzina-3574102/"
    "posts": 85981
  }, 
  {
    "category": "Duševno zdravje in odnosi",
    "forum": "Odnosi in socialna prva pomoč",
    "link": "https://med.over.net/forum/kategorija/dusevno-zdravje-in-odnosi/odnosi-in-socialna-prva-pomoc-3574418/"
    "posts": 58660
  },
  {
    ...
]
'''

def extract_forum_links(driver):
    forum_links = []
    forum_categories = driver.find_elements(By.CLASS_NAME, 'headline-table__text')
    forum_categories = [category.text.strip() for category in forum_categories]
    # print(forum_categories)
    
    tables = driver.find_elements(By.TAG_NAME, 'table')
    print(tables)
    for i, table in enumerate(tables):
        rows = table.find_elements(By.TAG_NAME, 'tr')
        for row in rows:
            forum_name = row.find_element(By.TAG_NAME, 'a')
            name = forum_name.text
            link = forum_name.get_attribute('href')
            posts = row.find_element(By.TAG_NAME, 'span').text
            forum_links.append({
                'category': forum_categories[i],
                'forum': name,
                'link': link,
                'posts': posts
            })
    
    return forum_links

In [31]:
forum_links = extract_forum_links(driver)
forum_links

[<selenium.webdriver.remote.webelement.WebElement (session="379b7b4e387acd4997edcee3d215d317", element="f.0FCA5813A5DA2657BE61E9B40561B4DB.d.2BC7FA3FF1C5D071E829A03F9BA67297.e.244")>, <selenium.webdriver.remote.webelement.WebElement (session="379b7b4e387acd4997edcee3d215d317", element="f.0FCA5813A5DA2657BE61E9B40561B4DB.d.2BC7FA3FF1C5D071E829A03F9BA67297.e.891")>, <selenium.webdriver.remote.webelement.WebElement (session="379b7b4e387acd4997edcee3d215d317", element="f.0FCA5813A5DA2657BE61E9B40561B4DB.d.2BC7FA3FF1C5D071E829A03F9BA67297.e.1408")>]

[{'category': 'Duševno zdravje in odnosi\nMapa forumov s temami o družini, medosebnih odnosih, prvi socialni pomoči, duševnemu zdravju, psihologija in psihiatriji.',
  'forum': 'Družina',
  'link': 'https://med.over.net/forum/kategorija/dusevno-zdravje-in-odnosi/druzina-3574102/',
  'posts': '86,041'},
 {'category': 'Duševno zdravje in odnosi\nMapa forumov s temami o družini, medosebnih odnosih, prvi socialni pomoči, duševnemu zdravju, psihologija in psihiatriji.',
  'forum': 'Odnosi in socialna prva pomoč',
  'link': 'https://med.over.net/forum/kategorija/dusevno-zdravje-in-odnosi/odnosi-in-socialna-prva-pomoc-3574418/',
  'posts': '58,796'},
 {'category': 'Duševno zdravje in odnosi\nMapa forumov s temami o družini, medosebnih odnosih, prvi socialni pomoči, duševnemu zdravju, psihologija in psihiatriji.',
  'forum': 'Psihologija in psihiatrija',
  'link': 'https://med.over.net/forum/kategorija/dusevno-zdravje-in-odnosi/psihologija-in-psihiatrija-3574431/',
  'posts': '16,247'},
 {'category': 'Duševno zdravje in odnosi\nMapa forumov s temami o družini, medosebnih odnosih, prvi socialni pomoči, duševnemu zdravju, psihologija in psihiatriji.',
  'forum': 'Arhiv Sociala',
  'link': 'https://med.over.net/forum/kategorija/dusevno-zdravje-in-odnosi/arhiv-sociala-22392520/',
  'posts': '3,412'},
 {'category': 'Zdravje',
  'forum': 'Bolezni srca in ožilja',
  'link': 'https://med.over.net/forum/kategorija/zdravje/bolezni-srca-in-ozilja-3574449/',
  'posts': '6,199'},
 {'category': 'Zdravje',
  'forum': 'Čutila',
  'link': 'https://med.over.net/forum/kategorija/zdravje/cutila-3574460/',
  'posts': '3,291'},
 {'category': 'Zdravje',
  'forum': 'Drugo',
  'link': 'https://med.over.net/forum/kategorija/zdravje/drugo-3574486/',
  'posts': '24,560'},
 {'category': 'Zdravje',
  'forum': 'Gibala/Gibalni sistem',
  'link': 'https://med.over.net/forum/kategorija/zdravje/gibala-gibalni-sistem-3574503/',
  'posts': '13,325'},
 {'category': 'Zdravje',
  'forum': 'Ginekologija',
  'link': 'https://med.over.net/forum/kategorija/zdravje/ginekologija-3574515/',
  'posts': '143,894'},
 {'category': 'Zdravje',
  'forum': 'Pediatrija',
  'link': 'https://med.over.net/forum/kategorija/zdravje/pediatrija-3574529/',
  'posts': '32,485'},
 {'category': 'Zdravje',
  'forum': 'Prebavila',
  'link': 'https://med.over.net/forum/kategorija/zdravje/prebavila-3574539/',
  'posts': '3,353'},
 {'category': 'Zdravje',
  'forum': 'Rak',
  'link': 'https://med.over.net/forum/kategorija/zdravje/rak-3574550/',
  'posts': '6,304'},
 {'category': 'Zdravje',
  'forum': 'Splošno',
  'link': 'https://med.over.net/forum/kategorija/zdravje/splosno-3574561/',
  'posts': '54,288'},
 {'category': 'Zdravje',
  'forum': 'Stomatologija',
  'link': 'https://med.over.net/forum/kategorija/zdravje/stomatologija-3574571/',
  'posts': '6,974'},
 {'category': 'Zdravje',
  'forum': 'Arhiv Zdravje',
  'link': 'https://med.over.net/forum/kategorija/zdravje/arhiv-zdravje-22349491/',
  'posts': '3,456'},
 {'category': 'Zdravje',
  'forum': 'Arhiv Zdravje HR',
  'link': 'https://med.over.net/forum/kategorija/zdravje/arhiv-zdravje-hr-22435178/',
  'posts': '407'},
 {'category': 'Življenjski slog',
  'forum': 'Alternativa',
  'link': 'https://med.over.net/forum/kategorija/zivljenjski-slog/alternativa-3574589/',
  'posts': '1,668'},
 {'category': 'Življenjski slog',
  'forum': 'Pravo in zavarovanja',
  'link': 'https://med.over.net/forum/kategorija/zivljenjski-slog/delo-pravo-zavarovanja-finance-3574599/',
  'posts': '2,907'},
 {'category': 'Življenjski slog',
  'forum': 'Prosti čas',
  'link': 'https://med.over.net/forum/kategorija/zivljenjski-slog/prosti-cas-3574612/',
  'posts': '51,231'},
 {'category': 'Življenjski slog',
  'forum': 'Spolnost',
  'link': 'https://med.over.net/forum/kategorija/zivljenjski-slog/spolnost-3574627/',
  'posts': '32,571'},
 {'category': 'Življenjski slog',
  'forum': 'Zdravo življenje',
  'link': 'https://med.over.net/forum/kategorija/zivljenjski-slog/zdravo-zivljenje-3574641/',
  'posts': '24,676'}]

In [43]:
driver.quit()

In [71]:
# Topics page lists different topics for a specific forum. Extract links to all the topics. Also take care of possible ads showing prior to content loading. Your function should return the following structure:

'''
[
  {
    "topic": "Dodatek za nego otroka, ki potrebuje posebno nego in varstvo nego",
    "answers": 14,
    "views": 564,
    "last-activity": "30.10.2023 ob 12:15",
    "link": "https://med.over.net/forum/tema/dodatek-za-nego-otroka-ki-potrebuje-posebno-nego-in-varstvo-nego-2069589/"
  }, 
  {
    "topic": "Preživnina",
    "answers": 2,
    "views": 19,
    "last-activity": "25.10.2023 ob 22:09",
    "link": "https://med.over.net/forum/tema/prezivnina-5-22508458/"
  },
  {
    ...
]
'''

def extract_topic_links(driver):
    topic_rows = driver.find_elements(By.CLASS_NAME, 'table-forum__row')
    topic_data = []
    for row in topic_rows:
        entries = row.find_elements(By.TAG_NAME, 'td')
        name = entries[0].text
        if name == 'TEMA':
            continue
        link = entries[0].find_element(By.TAG_NAME, 'a').get_attribute('href')
        answers = entries[1].find_element(By.TAG_NAME, 'span').text
        views = entries[2].text
        last_activity = entries[3].text
        topic_data.append({
            'topic': name,
            'answers': answers,
            'views': views,
            'last-activity': last_activity,
            'link': link
        })
        
    return topic_data

In [65]:
driver = webdriver.Chrome()
driver.get("https://med.over.net/forum/kategorija/dusevno-zdravje-in-odnosi/druzina-3574102/")
time.sleep(2)

In [72]:
# Test the function
topics = extract_topic_links(driver)

In [73]:
topics

[{'topic': 'Ebol list',
  'answers': '1',
  'views': '32',
  'last-activity': '08.11.2024 ob 09:50',
  'link': 'https://med.over.net/forum/tema/ebol-list-22553496/'},
 {'topic': 'Kaj si misliti o vsem tem',
  'answers': '1',
  'views': '337',
  'last-activity': '22.10.2024 ob 14:04',
  'link': 'https://med.over.net/forum/tema/kaj-si-misliti-o-vsem-tem-22544770/'},
 {'topic': 'Komunikator za Android',
  'answers': '8',
  'views': '64',
  'last-activity': '30.09.2024 ob 13:01',
  'link': 'https://med.over.net/forum/tema/komunikator-za-android-2973192/'},
 {'topic': 'Epilepsija brez diagnoze',
  'answers': '1',
  'views': '52',
  'last-activity': '23.09.2024 ob 06:13',
  'link': 'https://med.over.net/forum/tema/epilepsija-brez-diagnoze-22549459/'},
 {'topic': 'očetovski dopust ali bolniška',
  'answers': '2',
  'views': '101',
  'last-activity': '05.07.2024 ob 22:56',
  'link': 'https://med.over.net/forum/tema/ocetovski-dopust-ali-bolniska-22542052/'},
 {'topic': 'Brezplačno oz ugodno partnersko svetovanje',
  'answers': '1',
  'views': '62',
  'last-activity': '30.10.2024 ob 11:05',
  'link': 'https://med.over.net/forum/tema/brezplacno-oz-ugodno-partnersko-svetovanje-2-22552760/'},
 {'topic': 'Bojim se',
  'answers': '2',
  'views': '152',
  'last-activity': '29.10.2024 ob 15:57',
  'link': 'https://med.over.net/forum/tema/bojim-se-2-22552591/'},
 {'topic': 'Ali lahko sploh kaj storim',
  'answers': '2',
  'views': '278',
  'last-activity': '22.10.2024 ob 09:14',
  'link': 'https://med.over.net/forum/tema/ali-lahko-sploh-kaj-storim-22551585/'},
 {'topic': 'Prosim za nasvet',
  'answers': '1',
  'views': '164',
  'last-activity': '21.10.2024 ob 13:21',
  'link': 'https://med.over.net/forum/tema/prosim-za-nasvet-11-22551982/'},
 {'topic': 'Vem, da življenje ni potica, pa vendar?',
  'answers': '2',
  'views': '451',
  'last-activity': '04.10.2024 ob 15:43',
  'link': 'https://med.over.net/forum/tema/vem-da-zivljenje-ni-potica-pa-vendar-22550255/'},
 {'topic': 'posvojitev iz tujine',
  'answers': '4',
  'views': '295',
  'last-activity': '25.10.2024 ob 16:05',
  'link': 'https://med.over.net/forum/tema/posvojitev-iz-tujine-2-3413054/'},
 {'topic': 'Knjige o posvojitvi',
  'answers': '42',
  'views': '587',
  'last-activity': '17.10.2024 ob 16:39',
  'link': 'https://med.over.net/forum/tema/knjige-o-posvojitvi-2310397/'},
 {'topic': 'Posvojitev otroka ali ne situacija v afriki trenutno',
  'answers': '5',
  'views': '395',
  'last-activity': '27.09.2024 ob 23:47',
  'link': 'https://med.over.net/forum/tema/posvojitev-otroka-ali-ne-situacija-v-afriki-trenutno-3557418/'},
 {'topic': 'Posvojitev otroka iz afrike ali ne vprasanje??',
  'answers': '4',
  'views': '832',
  'last-activity': '23.09.2024 ob 12:20',
  'link': 'https://med.over.net/forum/tema/posvojitev-otroka-iz-afrike-ali-ne-vprasanje-3556561/'},
 {'topic': 'Posvojitev otroka iz Afrike',
  'answers': '21',
  'views': '516',
  'last-activity': '17.09.2024 ob 05:10',
  'link': 'https://med.over.net/forum/tema/posvojitev-otroka-iz-afrike-2396784/'},
 {'topic': 'Pesmica o dežju',
  'answers': '6',
  'views': '274',
  'last-activity': '07.11.2024 ob 03:08',
  'link': 'https://med.over.net/forum/tema/pesmica-o-dezju-459499/'},
 {'topic': 'Darilo za 6-letnico in 7-letnika',
  'answers': '5',
  'views': '626',
  'last-activity': '27.10.2024 ob 11:12',
  'link': 'https://med.over.net/forum/tema/darilo-za-6-letnico-in-7-letnika-272121/'},
 {'topic': 'Darilo za 5-letnika',
  'answers': '8',
  'views': '1287',
  'last-activity': '26.10.2024 ob 23:17',
  'link': 'https://med.over.net/forum/tema/darilo-za-5-letnika-2-424526/'},
 {'topic': 'Vegeta, jušne kocke',
  'answers': '9',
  'views': '83',
  'last-activity': '07.10.2024 ob 12:05',
  'link': 'https://med.over.net/forum/tema/vegeta-jusne-kocke-489653/'},
 {'topic': 'črna plesen v kopalnici na fugah',
  'answers': '11',
  'views': '3216',
  'last-activity': '07.10.2024 ob 01:08',
  'link': 'https://med.over.net/forum/tema/crna-plesen-v-kopalnici-na-fugah-328616/'}]

In [95]:
# Posts parsing
# Posts of a selected forum contain content. Extract posts data. Also take care of possible ads showing prior to content loading.
# Your function should return the following structure:

'''
[
  {
    "user": "petraT",
    "time": "14.10.2007 ob 23:47",
    "content": "Vlogo za dodatek za nego ...", #Extract whole text
  }, 
  {
    "user": "mamica, NEGA",
    "time": "06.12.2011 ob 12:17",
    "content": "Pozdravljeni! Za hčerko prejemam", #Extract whole text
  },
  {
    ...
]
'''

def extract_posts(driver):
    posts = driver.find_elements(By.CLASS_NAME, 'forum-post')
    post_data = []
    for post in posts:
        user_time = post.find_element(By.CLASS_NAME, 'forum-post__name')
        user = user_time.find_elements(By.TAG_NAME, 'span')[0].text
        time = user_time.find_elements(By.TAG_NAME, 'span')[1].text
        # content = post.find_element(By.TAG_NAME, 'p').text
        content = post.find_element(By.CLASS_NAME, 'forum-post__content').text
        post_data.append({
            'user': user,
            'time': time,
            'content': content
        })
        
    return post_data

In [96]:
driver = webdriver.Chrome()
driver.get("https://med.over.net/forum/tema/dodatek-za-nego-otroka-ki-potrebuje-posebno-nego-in-varstvo-nego-2069589/")
time.sleep(2)

In [97]:
posts = extract_posts(driver)

In [98]:
posts

[{'user': 'petraT',
  'time': '14.10.2007 ob 23:47',
  'content': 'Vlogo za dodatek za nego oddate na najbližjem CSD (vloga mora vsebovati tudi zdravstveno dokumentacijo: izvide in mnenja zdravnikov) in izpolnjen obrazec.\nNekaj več o dodatku za nego:\nhttp://www.csd-lj-siska.si/prejemki/dodatekNegaOtroka.asp\nhttp://www.csd-mb.si/sl/page/view/DodatekZaNegoOtroka\nPravna podlaga:\n– Zakona o starševskem varstvu in družinskih prejemkih (ZSDP-B)\n– P R A V I L N I K o kriterijih za uveljavljanje dodatka za nego otroka,\nhttp://www.uradni-list.si/1/objava.jsp?urlid=2002105&stevilka=5222\nhttp://www.uradni-list.si/1/objava.jsp?urlid=2006129&stevilka=5438\n(na koncu je trenutno veljaven seznam)\nLep pozdrav in lep dan, Petra'},
 {'user': 'mamica, NEGA',
  'time': '06.12.2011 ob 12:17',
  'content': 'Pozdravljeni!\nZa hčerko prejemam do leta 2013 dodatek za nego otroka, ki potrebuje posebno nego in varstvo nego, je otrok s posebnimi potrebami.\nAli bo hči morala ta dodatek vrniti državi po moji smrti?\nLp'},
 {'user': 'mamam',
  'time': '11.12.2011 ob 19:29',
  'content': 'Dodatka za nego ne bo potrebno vračat. Državi se bo vračalo dohodke ki so vezani na premoženjski cenzus; to je varstveni dodatek in socialna podpora.\nObčini se pa vrača nadomestilo za izgubljeni dohodek, ki ga prejema družinski pomočnik po otrokovem 18.letu in doplačilo kritja stroškov v bivalnih skupnostih in podobnih ustanovah.\nJe pa razumevanje vračila velikokrat napačno. Če prejemate podporo za otroka je dolžnik državi (ali občini) otrok, ne vi. Torej po otrokovi smrti(ne vaši, (v primeru da ste nadomestilo za izgubljeni dohodek prejemala vi)), če bo imel kaj premoženja se bo najprej odvzelo dolg, ostalo pa ostane za dedovanje(če je še kaj). Če premoženja nima tudi vračila ni. Vsekakor nikomur ni potrebno zalagat za sorodnikove dolgove.'},
 {'user': 'majdamajda123',
  'time': '03.02.2013 ob 21:10',
  'content': 'Dodatek za nego smo dobivali do decembra 2012, letos pa nam je potekla pogodba. Kako se lahko dodatek ponovno pridobi? Sin ima status študenta s posebnimi potrebami in kolikor sem spremljala, smo do dodatka uravečni v času šolanja… Je treba ponovno mnenje komisije, vsa dokumentacija in celoten postopek, kot da dodatka še ne bi prejemali?\nNajleša hvala\nMajda'},
 {'user': 'petraT',
  'time': '05.02.2013 ob 07:38',
  'content': 'Majda,\nlahko poskuite vložiti novo vlogo z novimi izvidi,ampak večinoma je trajanje dodatka za nego v večini primerov časovno omejeno.'},
 {'user': 'majdamajda123',
  'time': '07.02.2013 ob 14:17',
  'content': 'Najlepša hvala!'},
 {'user': 'fani švab',
  'time': '19.02.2013 ob 11:31',
  'content': 'Spoštovani!\nSem prejemnica dodatka za nego otroka,ker je hči zbolela za sladkorno boleznijo tipa1.\nZanima me,če se ta dodatek tretita kot dohodek(glede na to,da ga dobi vsak bolan otrok,ne glede na dohodke starša ali družine),če zaprosiš za socialno pomoč in se potemtakem od višine le te odšteje!?\nHvala za odgovor!'},
 {'user': 'roza73',
  'time': '30.03.2013 ob 06:59',
  'content': 'pozdravljeni….imam eno vprašanje….imam sina starega 4leta in pol in je otrok s posebnimi potrebani……takrat ko se je rodil oz ko je bil še mlajši nisem vedela da lahko uveljavljam pravice za nego in za izgubljeni dohodek. sem pa pred časom izvedela da lahko in sem za nego dobila odločbo pozitivno,za izgubljeni dohodek pa so mi na centru rekli da so izvidi prestari in da moram pridobiti novejše izvide….mislim meni to ni logično če je diagnoza enkrat potrjena ne vem zakaj potem zahtevajo novo.izvidi so pa iz leta 2010-2012. prosim povejte mi kaj naj naredim?'},
 {'user': 'petraT',
  'time': '03.04.2013 ob 15:57',
  'content': 'Žal se šteje trenutno vsak prihodek, tudi dodatek za nego.'},
 {'user': 'petraT',
  'time': '03.04.2013 ob 15:58',
  'content': 'Roza73,\nimate nižji ali višji dodatek za nego?'},
 {'user': 'S. Lenarčič',
  'time': '14.01.2014 ob 20:41',
  'content': 'Moj sin ima celiakijo in dobiva dodatek za nego. Preden je bil star 18 let sem na CSD Postojna poslala prošnjo za podaljšanje in potrdilo o šolanju. Ker prošnja ni bila na ustreznem obrazcu, so mi dodatek ukinili. pritožila sem se in na ministrstvu so pozitivno rešili pritožbo. Po enem letu sem dobila dodatek za nazaj, obresti pa ne. mislim, da sem upravičena tudi do obresti. če bi bila jaz dolžna državi, bi morala plačati obresti.\nLep dan!\nStanka'},
 {'user': 'mamicaPP10',
  'time': '28.02.2014 ob 11:41',
  'content': 'Zdravo,\nmene pa zanima, kako je z uveljavljanjem otroka s PP (dodatek za nego) v dohodnini. Ker odločba je od sredine leta naprej za eno leto. To pomeni, da ga lahko uveljavljam le za pol leta ali za celo leto 2013?\nHvala in lp\nmamicaPP10'},
 {'user': 'petraT',
  'time': '01.03.2014 ob 12:20',
  'content': 'mamica PP10,\nod takrat, ko je odločba izdana do konca leta kot A5 – v bistvu bi lahko že na obrazcu otroka kot označili kot A5.'},
 {'user': 'enamamasončica',
  'time': '04.03.2014 ob 14:16',
  'content': 'Meni so na DURS-u pred leti upoštevali odločbo o dodatku za nego (in kategorijo A5) samo za mesece veljavnosti odločbe, pri ostalih mesecih pa pač tisto splošno olajšavo za otroka.\nLP,\nenamamasončica'}]

In [94]:
driver.quit()

In [99]:
# ## Task 4: End-to-end parsing

# Extract all data without manual supervision. Extract only data from *first pages* (i.e., there is no need to paginate to retrieve all topics, posts). Also take care of possible ads showing prior to content loading.

# The result of parsing should be stored in a pandas data frame, containing the following columns: > category, forum, posts-number, topic-answers, topic-views, topic-last-activity, user, user-post-time, user-content


def extract_data(driver):
    MAIN_URL = 'https://med.over.net/forum'
    driver.get(MAIN_URL)
    time.sleep(2)
    forum_links = extract_forum_links(driver)
    data = []
    for forum_link in forum_links[:2]:
        driver.get(forum_link['link'])
        time.sleep(2)
        topics = extract_topic_links(driver)
        for topic in topics[:2]:
            driver.get(topic['link'])
            time.sleep(2)
            posts = extract_posts(driver)
            for post in posts[:2]:
                data.append({
                    'category': forum_link['category'],
                    'forum': forum_link['forum'],
                    'posts-number': forum_link['posts'],
                    'topic-answers': topic['answers'],
                    'topic-views': topic['views'],
                    'topic-last-activity': topic['last-activity'],
                    'user': post['user'],
                    'user-post-time': post['time'],
                    'user-content': post['content']
                })
    return pd.DataFrame(data)

In [100]:
driver = webdriver.Chrome()
data = extract_data(driver)
data

[<selenium.webdriver.remote.webelement.WebElement (session="23b2890b5dd01bc27cbb9cf3b3eb8c1a", element="f.77CA50DBA9214BD3FF7FD13E9BAA7203.d.64D41B40247E9E7EB9D8E277616277A0.e.148")>, <selenium.webdriver.remote.webelement.WebElement (session="23b2890b5dd01bc27cbb9cf3b3eb8c1a", element="f.77CA50DBA9214BD3FF7FD13E9BAA7203.d.64D41B40247E9E7EB9D8E277616277A0.e.149")>, <selenium.webdriver.remote.webelement.WebElement (session="23b2890b5dd01bc27cbb9cf3b3eb8c1a", element="f.77CA50DBA9214BD3FF7FD13E9BAA7203.d.64D41B40247E9E7EB9D8E277616277A0.e.150")>]

,category,forum,posts-number,topic-answers,topic-views,topic-last-activity,user,user-post-time,user-content
0,Duševno zdravje in odnosi\nMapa forumov s tema...,Družina,"86,041",1,33,08.11.2024 ob 09:50,zmedena808,08.11.2024 ob 09:50,lahko kot zaposlena sama dvignem Ebol list na ...
1,Duševno zdravje in odnosi\nMapa forumov s tema...,Družina,"86,041",1,338,22.10.2024 ob 14:04,Mamica137,31.07.2024 ob 13:37,"Pozdravljeni,\ns partnerjem sva bila dolgo sku..."
2,Duševno zdravje in odnosi\nMapa forumov s tema...,Odnosi in socialna prva pomoč,"58,796",7,368,10.11.2024 ob 09:14,zelenook36,10.01.2024 ob 09:37,"Pozdravljene,\nsem prijazen, preprost, urejen,..."
3,Duševno zdravje in odnosi\nMapa forumov s tema...,Odnosi in socialna prva pomoč,"58,796",7,368,10.11.2024 ob 09:14,zelenook36,18.03.2024 ob 08:25,"Pozdravljene,\nsem prijazen, preprost, urejen,..."
4,Duševno zdravje in odnosi\nMapa forumov s tema...,Odnosi in socialna prva pomoč,"58,796",3,68,10.11.2024 ob 09:12,Klemen526,04.11.2024 ob 13:21,"Pozdravljeni,\nSem 25 letni fant, ki se zadnje..."
5,Duševno zdravje in odnosi\nMapa forumov s tema...,Odnosi in socialna prva pomoč,"58,796",3,68,10.11.2024 ob 09:12,Živjo268,05.11.2024 ob 19:36,"Klemen! Ne sekiraj se, kakorkoli se boš odloči..."

In [101]:
data.to_csv('data/med_over_net.csv', index=False)

In [102]:
driver.quit()

In [104]:
# ## Task 5: Data cleaning

# Clean the data in the following way:
# - Remove duplicates
# - Remove rows with missing values
# - Convert columns to appropriate data types
# - Remove leading/trailing whitespaces in columns
# - Remove rows where the user is a bot (i.e., the user contains the word "bot")
# - Remove rows where the user has less than 3 characters


data = pd.read_csv('data/med_over_net.csv')

# Remove duplicates
data = data.drop_duplicates()

# Remove rows with missing values
data = data.dropna()

# Convert columns to appropriate data types
data['topic-answers'] = data['topic-answers'].astype(int)
data['topic-views'] = data['topic-views'].astype(int)

# Remove leading/trailing whitespaces in columns
data['category'] = data['category'].str.strip()
data['forum'] = data['forum'].str.strip()
data['user'] = data['user'].str.strip()
data['user-content'] = data['user-content'].str.strip()

# Remove rows where the user is a bot (i.e., the user contains the word "bot")
data = data[~data['user'].str.contains('bot', case=False)]

# Remove rows where the user has less than 3 characters
data = data[data['user'].str.len() >= 3]

data

,category,forum,posts-number,topic-answers,topic-views,topic-last-activity,user,user-post-time,user-content
0,Duševno zdravje in odnosi\nMapa forumov s tema...,Družina,"86,041",1,33,08.11.2024 ob 09:50,zmedena808,08.11.2024 ob 09:50,lahko kot zaposlena sama dvignem Ebol list na ...
1,Duševno zdravje in odnosi\nMapa forumov s tema...,Družina,"86,041",1,338,22.10.2024 ob 14:04,Mamica137,31.07.2024 ob 13:37,"Pozdravljeni,\ns partnerjem sva bila dolgo sku..."
2,Duševno zdravje in odnosi\nMapa forumov s tema...,Odnosi in socialna prva pomoč,"58,796",7,368,10.11.2024 ob 09:14,zelenook36,10.01.2024 ob 09:37,"Pozdravljene,\nsem prijazen, preprost, urejen,..."
3,Duševno zdravje in odnosi\nMapa forumov s tema...,Odnosi in socialna prva pomoč,"58,796",7,368,10.11.2024 ob 09:14,zelenook36,18.03.2024 ob 08:25,"Pozdravljene,\nsem prijazen, preprost, urejen,..."
4,Duševno zdravje in odnosi\nMapa forumov s tema...,Odnosi in socialna prva pomoč,"58,796",3,68,10.11.2024 ob 09:12,Klemen526,04.11.2024 ob 13:21,"Pozdravljeni,\nSem 25 letni fant, ki se zadnje..."
5,Duševno zdravje in odnosi\nMapa forumov s tema...,Odnosi in socialna prva pomoč,"58,796",3,68,10.11.2024 ob 09:12,Živjo268,05.11.2024 ob 19:36,"Klemen! Ne sekiraj se, kakorkoli se boš odloči..."

In [105]:
data['user'].unique()

array(['zmedena808', 'Mamica137', 'zelenook36', 'Klemen526', 'Živjo268'],
      dtype=object)

In [109]:
data.groupby('forum')['user'].nunique()

forum
Družina                          2
Odnosi in socialna prva pomoč    3
Name: user, dtype: int64