In [19]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, TimeoutException
import time
import pandas as pd

In [36]:
MAIN_URL = 'https://fri.uni-lj.si/sl/o-fakulteti/osebje'

driver = webdriver.Chrome()
driver.get(MAIN_URL)

listed_by_letter = driver.find_elements(By.CLASS_NAME, 'listedProf')

In [37]:
for list in listed_by_letter:
    print(list.text)
    print('------------------')

Marija Absec
Areeb Ahmed
Špela Antloga
Tjaša Arčon
Špela Arhar Holdt
Nina Arko Krmelj
Fatemeh Azad
------------------
Marko Bajec
Borut Batagelj
Andrej Bauer
Miha Bejek
Simon Bele
Aljoša Besednjak
Luka Bezgovšek
Marko Boben
Ciril Bohak
Alenka Bone
Tadej Borovšak
Zoran Bosnić
Narvika Bovcon
Ivan Bratko
Marko Brodarič
Andrej Brodnik
Patricio Bulić
------------------
Tilen Celjer
Mojca Ciglarič
Dekan
Zala Cimperman
Tomaž Curk
Prodekan
Jernej Cvek
------------------
Luka Čehovin Zajc
Rok Češnovar
Jaka Čibej
Uroš Čibej
Božica Čulibrk Rajkovič
------------------
Andrea De Gobbis
Harun Demir
Janez Demšar
Jure Demšar
Tomaž Dobravec
Matej Dobrevski
------------------
Žiga Emeršič
Dániel Erdélyhegyi
Aleš Erjavec
------------------
Jana Faganeli Pucer
Gašper Fele Žorž
Gašper Fijavž
Marko Firm
Borut Flis
Aleksandra Franc
Damir Franetič
Matic Fučka
Damjan Fujs
Svetlana Fuks
Erika Funa
Luka Fürst
------------------
Gregor Gabrovšek
Peter Gabrovšek
Timotej Gale
Kaja Gantar
Apolonija Gantar
Bruno Gašperov
Sandi Gec
Dejan Georgiev
Atiyeh Ghane
Martin Gjoreski
Primož Godec
Saša Gojić
Rok Gomišček
Peter Goričan
Vesna Gračner
Andrej Grebenc
Rok Gregorin
Miha Grohar
Vida Groznik
Zala Gruden
Matej Guid
------------------
Ana Halužan Vasle
Tomaž Hočevar
Tomaž Hovelja
Aleks Huč
Kama Hudobivnik
Ana Hvastija
Leon Hvastja
------------------
Nejc Ilc
------------------
Franc Jager
Aleš Jaklič
Miha Janež
Stefana Janičijević
David Jelenc
Gašper Jelovčan
Gregor Jerše
Branko Matjaž Jurič
Aleksandar Jurišić
Arvin Jušić
Andraž Juvan
Jure Juvan
------------------
Tadej Kanduč
Aneta Kartali
Alenka Kavčič
Borut Paul Kerševan
Peter Marijan Kink
Klavdija Kitek
Klemen Klanjšček
Matej Klemen
Bojan Klemenc
Vid Klopčič
Timotej Knez
Petar Kochovski
Jaka Kokošar
Boshko Koloski
Igor Kononenko
Miran Koprivec
Sara Kos
Iztok Kosem
Domen Košir
Simon Krek
Matej Kristan
Yannick Kuhar
Matjaž Kukar
------------------
Romanela Lajić
Ajda Lampe
Leon Lampret
Iztok Lapanja
Nicolas Larue
Cyprian Adam Laskowski
Dejan Lavbič
Timotej Lazar
Iztok Lebar Bajec
Aleš Leonardis
Žiga Lesar
Jure Leskovec
André Lezan Fernandes
Nikola Ljubešić
Sonja Lojk
Matija Lokar
Uroš Lotrič
Alan Lukežič
Aleksandra Lutar Ivanc
------------------
Luka Maček
Nives Macerl
Tajnik fakultete
Alina - Luminita Machidon
Octavian Mihai Machidon
Marta Malavolta
Miha Malenšek
Mateja Malešič
Luka Mali
Mila Marinković
Jernej Markelj
Matija Marolt
Teodora Matić
Mateja Mavrič
Blaž Meden
Daša Mesarič Štesl
Jan Meznarič
Nataša Mihalič
Anže Mihelič
Jurij Mihelič
Vanja Mileski
Pouriya Miri
Teodora Mishevska Kochovski
David Modic
Miha Moškon
Prodekan
Martin Možina
Nežka Mramor Kosta
Miha Mraz
Jon Natanael Muhovič
------------------
David Nabergoj
Mimoza Naseka
Andreja Nič
Jakob Novak
------------------
Polona Oblak
Tim Oblak
Saša Ogrizović
Bojan Orel
------------------
Neža Pajek Arambašič
Matjaž Pančur
Petar Pavešić
Peter Peer
Veljko Pejović
Jer Pelhan
Matevž Pesek
Bernarda Petek
Andrej Petelin
Matej Pičulin
Ratko Pilipović
Žiga Pirnar
Teodor Janez Podobnik
Vid Podpečan
Gaber Polajnar
Pavlin Gregor Poličar
Senja Pollak
Damjan Popič
Aleš Popovič
Eva Pori
Mitja Potočar
Marko Poženel
Ela Praznik
Ajda Pretnar Žagar
Žiga Pušnik
------------------
Mihael Rajh
Vid Rijavec
Mitja Rizvič
Borut Robič
Nejc Robida
Rebeka Roblek
Marko Robnik Šikonja
Blaž Rolih
Peter Rot
Igor Rožanc
Ksenija Rozman
Robert Rozman
Taja Runovc
Rok Rupnik
Marko Rus
------------------
Aleksander Sadikov
Miha Schaffer
Qomri Sholeh
Petra Simonič
Danijel Skočaj
Jasmina Slapničar
Tadej Slemenšek
Boštjan Slivnik
Davor Sluga
Aleš Smonig Grnjak
Aleš Smrdel
Franc Solina
Vlado Stankovski
Prodekan
Lidija Stanovnik
Mojca Svetek
------------------
Luka Šajn
Josip Šarić
Meta Šeruga
Andrej Šeruga
Iztok Škof
Blaž Škrlj
Tadej Škvorc
Uroš Šmajdek
Domen Šoberl
Tjaša Šoltes
Martin Špendl
Maja Špolad
Branko Šter
Erik Štrumbelj
Lovro Šubelj
------------------
Domen Tabernik
Vesna Tanko
Luka Terčon
Darian Tomašević
Marko Toplak
Barbara Torkar
Denis Trček
Mira Trebar
Jernej Trnkoczy
Klemen Turkovič
Jure Tuta
------------------
Damjan Vavpotič
Prodekan
Zdenka Velikonja
Kristina Veljković
Melanija Vezočnik
Janoš Vidali
Urša Vidic
Martin Vidmar
Žiga Virk
Matej Vitek
Jaka Vodeb
Irena von Arx Ograjenšek
Petar Vračar
Domen Vreš
Simon Vrhovec
Martin Vuk
------------------
Aleš Watzak
------------------
Aljaž Zalar
Vitjan Zavrtanik
Marko Zeman
Karolina Zgaga
Nikolaj Zimic
Maj Zirkelbach
Aljaž Zrnec
Dani Zugan
Helena Marija Zupan
Blaž Zupan
Teja Zupančič
------------------
Jure Žabkar
Aleš Žagar
Lan Žagar
Manca Žerovnik Mekuč
Janez Žibert
Rok Žitko
Slavko Žitnik
Prodekan
Urška Žnidarič
Klara Žnideršič
Bojan Žunkovič
Lojze Žust
------------------

In [25]:
for list in listed_by_letter:
    for prof in list.find_elements(By.TAG_NAME, 'a'):
        print(prof.text)
        print('------------------')

Marija Absec
------------------
Areeb Ahmed
------------------
Špela Antloga
------------------
Tjaša Arčon
------------------
Špela Arhar Holdt
------------------
Nina Arko Krmelj
------------------
Fatemeh Azad
------------------
Marko Bajec
------------------
Borut Batagelj
------------------
Andrej Bauer
------------------
Miha Bejek
------------------
Simon Bele
------------------
Aljoša Besednjak
------------------
Luka Bezgovšek
------------------
Marko Boben
------------------
Ciril Bohak
------------------
Alenka Bone
------------------
Tadej Borovšak
------------------
Zoran Bosnić
------------------
Narvika Bovcon
------------------
Ivan Bratko
------------------
Marko Brodarič
------------------
Andrej Brodnik
------------------
Patricio Bulić
------------------
Tilen Celjer
------------------
Mojca Ciglarič
Dekan
------------------
Zala Cimperman
------------------
Tomaž Curk
Prodekan
------------------
Jernej Cvek
------------------
Luka Čehovin Zajc
------------------
Rok Češnovar
------------------
Jaka Čibej
------------------
Uroš Čibej
------------------
Božica Čulibrk Rajkovič
------------------
Andrea De Gobbis
------------------
Harun Demir
------------------
Janez Demšar
------------------
Jure Demšar
------------------
Tomaž Dobravec
------------------
Matej Dobrevski
------------------
Žiga Emeršič
------------------
Dániel Erdélyhegyi
------------------
Aleš Erjavec
------------------
Jana Faganeli Pucer
------------------
Gašper Fele Žorž
------------------
Gašper Fijavž
------------------
Marko Firm
------------------
Borut Flis
------------------
Aleksandra Franc
------------------
Damir Franetič
------------------
Matic Fučka
------------------
Damjan Fujs
------------------
Svetlana Fuks
------------------
Erika Funa
------------------
Luka Fürst
------------------
Gregor Gabrovšek
------------------
Peter Gabrovšek
------------------
Timotej Gale
------------------
Kaja Gantar
------------------
Apolonija Gantar
------------------
Bruno Gašperov
------------------
Sandi Gec
------------------
Dejan Georgiev
------------------
Atiyeh Ghane
------------------
Martin Gjoreski
------------------
Primož Godec
------------------
Saša Gojić
------------------
Rok Gomišček
------------------
Peter Goričan
------------------
Vesna Gračner
------------------
Andrej Grebenc
------------------
Rok Gregorin
------------------
Miha Grohar
------------------
Vida Groznik
------------------
Zala Gruden
------------------
Matej Guid
------------------
Ana Halužan Vasle
------------------
Tomaž Hočevar
------------------
Tomaž Hovelja
------------------
Aleks Huč
------------------
Kama Hudobivnik
------------------
Ana Hvastija
------------------
Leon Hvastja
------------------
Nejc Ilc
------------------
Franc Jager
------------------
Aleš Jaklič
------------------
Miha Janež
------------------
Stefana Janičijević
------------------
David Jelenc
------------------
Gašper Jelovčan
------------------
Gregor Jerše
------------------
Branko Matjaž Jurič
------------------
Aleksandar Jurišić
------------------
Arvin Jušić
------------------
Andraž Juvan
------------------
Jure Juvan
------------------
Tadej Kanduč
------------------
Aneta Kartali
------------------
Alenka Kavčič
------------------
Borut Paul Kerševan
------------------
Peter Marijan Kink
------------------
Klavdija Kitek
------------------
Klemen Klanjšček
------------------
Matej Klemen
------------------
Bojan Klemenc
------------------
Vid Klopčič
------------------
Timotej Knez
------------------
Petar Kochovski
------------------
Jaka Kokošar
------------------
Boshko Koloski
------------------
Igor Kononenko
------------------
Miran Koprivec
------------------
Sara Kos
------------------
Iztok Kosem
------------------
Domen Košir
------------------
Simon Krek
------------------
Matej Kristan
------------------
Yannick Kuhar
------------------
Matjaž Kukar
------------------
Romanela Lajić
------------------
Ajda Lampe
------------------
Leon Lampret
------------------
Iztok Lapanja
------------------
Nicolas Larue
------------------
Cyprian Adam Laskowski
------------------
Dejan Lavbič
------------------
Timotej Lazar
------------------
Iztok Lebar Bajec
------------------
Aleš Leonardis
------------------
Žiga Lesar
------------------
Jure Leskovec
------------------
André Lezan Fernandes
------------------
Nikola Ljubešić
------------------
Sonja Lojk
------------------
Matija Lokar
------------------
Uroš Lotrič
------------------
Alan Lukežič
------------------
Aleksandra Lutar Ivanc
------------------
Luka Maček
------------------
Nives Macerl
Tajnik fakultete
------------------
Alina - Luminita Machidon
------------------
Octavian Mihai Machidon
------------------
Marta Malavolta
------------------
Miha Malenšek
------------------
Mateja Malešič
------------------
Luka Mali
------------------
Mila Marinković
------------------
Jernej Markelj
------------------
Matija Marolt
------------------
Teodora Matić
------------------
Mateja Mavrič
------------------
Blaž Meden
------------------
Daša Mesarič Štesl
------------------
Jan Meznarič
------------------
Nataša Mihalič
------------------
Anže Mihelič
------------------
Jurij Mihelič
------------------
Vanja Mileski
------------------
Pouriya Miri
------------------
Teodora Mishevska Kochovski
------------------
David Modic
------------------
Miha Moškon
Prodekan
------------------
Martin Možina
------------------
Nežka Mramor Kosta
------------------
Miha Mraz
------------------
Jon Natanael Muhovič
------------------
David Nabergoj
------------------
Mimoza Naseka
------------------
Andreja Nič
------------------
Jakob Novak
------------------
Polona Oblak
------------------
Tim Oblak
------------------
Saša Ogrizović
------------------
Bojan Orel
------------------
Neža Pajek Arambašič
------------------
Matjaž Pančur
------------------
Petar Pavešić
------------------
Peter Peer
------------------
Veljko Pejović
------------------
Jer Pelhan
------------------
Matevž Pesek
------------------
Bernarda Petek
------------------
Andrej Petelin
------------------
Matej Pičulin
------------------
Ratko Pilipović
------------------
Žiga Pirnar
------------------
Teodor Janez Podobnik
------------------
Vid Podpečan
------------------
Gaber Polajnar
------------------
Pavlin Gregor Poličar
------------------
Senja Pollak
------------------
Damjan Popič
------------------
Aleš Popovič
------------------
Eva Pori
------------------
Mitja Potočar
------------------
Marko Poženel
------------------
Ela Praznik
------------------
Ajda Pretnar Žagar
------------------
Žiga Pušnik
------------------
Mihael Rajh
------------------
Vid Rijavec
------------------
Mitja Rizvič
------------------
Borut Robič
------------------
Nejc Robida
------------------
Rebeka Roblek
------------------
Marko Robnik Šikonja
------------------
Blaž Rolih
------------------
Peter Rot
------------------
Igor Rožanc
------------------
Ksenija Rozman
------------------
Robert Rozman
------------------
Taja Runovc
------------------
Rok Rupnik
------------------
Marko Rus
------------------
Aleksander Sadikov
------------------
Miha Schaffer
------------------
Qomri Sholeh
------------------
Petra Simonič
------------------
Danijel Skočaj
------------------
Jasmina Slapničar
------------------
Tadej Slemenšek
------------------
Boštjan Slivnik
------------------
Davor Sluga
------------------
Aleš Smonig Grnjak
------------------
Aleš Smrdel
------------------
Franc Solina
------------------
Vlado Stankovski
Prodekan
------------------
Lidija Stanovnik
------------------
Mojca Svetek
------------------
Luka Šajn
------------------
Josip Šarić
------------------
Meta Šeruga
------------------
Andrej Šeruga
------------------
Iztok Škof
------------------
Blaž Škrlj
------------------
Tadej Škvorc
------------------
Uroš Šmajdek
------------------
Domen Šoberl
------------------
Tjaša Šoltes
------------------
Martin Špendl
------------------
Maja Špolad
------------------
Branko Šter
------------------
Erik Štrumbelj
------------------
Lovro Šubelj
------------------
Domen Tabernik
------------------
Vesna Tanko
------------------
Luka Terčon
------------------
Darian Tomašević
------------------
Marko Toplak
------------------
Barbara Torkar
------------------
Denis Trček
------------------
Mira Trebar
------------------
Jernej Trnkoczy
------------------
Klemen Turkovič
------------------
Jure Tuta
------------------
Damjan Vavpotič
Prodekan
------------------
Zdenka Velikonja
------------------
Kristina Veljković
------------------
Melanija Vezočnik
------------------
Janoš Vidali
------------------
Urša Vidic
------------------
Martin Vidmar
------------------
Žiga Virk
------------------
Matej Vitek
------------------
Jaka Vodeb
------------------
Irena von Arx Ograjenšek
------------------
Petar Vračar
------------------
Domen Vreš
------------------
Simon Vrhovec
------------------
Martin Vuk
------------------
Aleš Watzak
------------------
Aljaž Zalar
------------------
Vitjan Zavrtanik
------------------
Marko Zeman
------------------
Karolina Zgaga
------------------
Nikolaj Zimic
------------------
Maj Zirkelbach
------------------
Aljaž Zrnec
------------------
Dani Zugan
------------------
Helena Marija Zupan
------------------
Blaž Zupan
------------------
Teja Zupančič
------------------
Jure Žabkar
------------------
Aleš Žagar
------------------
Lan Žagar
------------------
Manca Žerovnik Mekuč
------------------
Janez Žibert
------------------
Rok Žitko
------------------
Slavko Žitnik
Prodekan
------------------
Urška Žnidarič
------------------
Klara Žnideršič
------------------
Bojan Žunkovič
------------------
Lojze Žust
------------------

In [17]:
#WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, "//button[contains(text(), 'Soglašam')]"))).click()

In [64]:
df = pd.DataFrame(columns=['Name', 'Title', 'Number', 'Number of courses', 'Number of projects'])
df

Empty DataFrame
Columns: [Name, Title, Number, Number of courses, Number of projects]
Index: []

In [38]:
profile_urls = []
for list in listed_by_letter:
    prof_links = list.find_elements(By.TAG_NAME, 'a')
    for prof in prof_links:
        profile_urls.append(prof.get_attribute('href'))  # Store the href of each link

In [69]:
len(profile_urls)

293

In [76]:
for url in profile_urls[11:]:
    driver.get(url)
    time.sleep(2) 

    # Wait for the 'profName' element to be visible, up to 10 seconds
    prof_name = WebDriverWait(driver, 10).until(
        EC.visibility_of_element_located((By.ID, 'profName'))
    ).text

     # Similarly wait for 'profTitle' and 'telephoneInfo' elements
    prof_title = WebDriverWait(driver, 10).until(
        EC.visibility_of_element_located((By.ID, 'profTitle'))
    ).text
    
    try:
        prof_number_element = WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.ID, 'telephoneInfo'))
        )
        prof_number = prof_number_element.text if prof_number_element else ""
    except TimeoutException:
        prof_number = ""
        
    # Courses
    num_courses = 0
    headers = driver.find_elements(By.CLASS_NAME, "aboutMainSectionContainer")
    for header in headers:
        # print(header.text)
        if "PREDMETI" in header.text:
            courses_div = header.find_element(By.CLASS_NAME, "aboutMainSectionLi")
            courses_list = courses_div.find_element(By.TAG_NAME, "ul")
            course_items = courses_list.find_elements(By.TAG_NAME, "li")
            num_courses = len(course_items)
            break
            
    # Projects
    num_active_projects = 0
    num_completed_projects = 0
    for header in headers:
        if "PROJEKTI" in header.text:
            projects_div = header.find_element(By.CLASS_NAME, "aboutMainSectionLi")
            projects_list = projects_div.find_elements(By.TAG_NAME, "ul")
            # print(projects_list)
            project_items = projects_list[0].find_elements(By.TAG_NAME, "li")
            num_active_projects = len(project_items)
            if len(projects_list) > 1:
                completed_project_items = projects_list[1].find_elements(By.TAG_NAME, "li")
                num_completed_projects = len(completed_project_items)
            
    total_projects = num_active_projects + num_completed_projects

    length = len(df)
    df.loc[length] = {
        'Name': prof_name,
        'Title': prof_title,
        'Number': prof_number,
        'Number of courses': num_courses,
        'Number of projects': total_projects
    }
    
    print(f"{prof_name} - {prof_title} - {prof_number} - Courses: {num_courses} - Projects: {total_projects}")

Simon Bele - Tehniški sodelavec -  - Courses: 0 - Projects: 1
Aljoša Besednjak - Vzdrževalec - T: +386 41 304 743 - Courses: 0 - Projects: 0
Luka Bezgovšek - Tehniški sodelavec -  - Courses: 0 - Projects: 0
asist. dr. Marko Boben - Asistent - T: +386 1 479 8258 - Courses: 1 - Projects: 1
doc. dr. Ciril Bohak - Docent - T: +386 1 479 8259 - Courses: 4 - Projects: 15
Alenka Bone - Kadrovska služba - T: +386 1 4798115 - Courses: 0 - Projects: 0
Tadej Borovšak - Drugi člani -  - Courses: 0 - Projects: 0
prof. dr. Zoran Bosnić - Redni profesor - T: +386 1 479 8237 - Courses: 18 - Projects: 21
prof. dr. Narvika Bovcon - Redni profesor - T: +386 1 479 8272 - Courses: 5 - Projects: 5
prof. dr. Ivan Bratko - Raziskovalec - T: +386 1 479 8287 - Courses: 4 - Projects: 12
Marko Brodarič - Raziskovalec -  - Courses: 0 - Projects: 1
doc. dr. Andrej Brodnik - Docent - T: +386 1 479 8263 - Courses: 3 - Projects: 26
prof. dr. Patricio Bulić - Redni profesor - T: +386 1 479 8255 - Courses: 3 - Projects: 17
Tilen Celjer - Dekanat - T: +38614798111 - Courses: 0 - Projects: 0
izr. prof. dr. Mojca Ciglarič - Izredni profesor
Dekan - T: +386 1 479 8205 - Courses: 2 - Projects: 31
Zala Cimperman - Dekanat - T: +386 1 479 8103 - Courses: 0 - Projects: 0
izr. prof. dr. Tomaž Curk - Izredni profesor
Prodekan - T: +386 1 479 8229 - Courses: 18 - Projects: 27
Jernej Cvek - Tehniški sodelavec -  - Courses: 0 - Projects: 2
doc. dr. Luka Čehovin Zajc - Asistent - T: +386 1 479 8252 - Courses: 3 - Projects: 10
pred. dr. Rok Češnovar - Asistent - T: +386 1 479 8231 - Courses: 2 - Projects: 9
znan. sod. dr. Jaka Čibej - Drugi člani -  - Courses: 0 - Projects: 3
doc. dr. Uroš Čibej - Asistent - T: +386 1 479 8213 - Courses: 5 - Projects: 9
Božica Čulibrk Rajkovič - Služba za raziskovalno dejavnost -  - Courses: 0 - Projects: 0
Andrea De Gobbis - Raziskovalec -  - Courses: 0 - Projects: 0
Harun Demir - Tehniški sodelavec -  - Courses: 0 - Projects: 0
prof. dr. Janez Demšar - Redni profesor - Govorilne ure: Po dogovoru - Courses: 5 - Projects: 21
doc. dr. Jure Demšar - Drugi člani - T: +386 1 479 8204 - Courses: 2 - Projects: 1
doc. dr. Tomaž Dobravec - Docent - T: +386 1 479 8256 - Courses: 4 - Projects: 9
asist. dr. Matej Dobrevski - Asistent -  - Courses: 2 - Projects: 0
doc. dr. Žiga Emeršič - Asistent - T: +386 1 4798 240 - Courses: 3 - Projects: 6
Dániel Erdélyhegyi - Raziskovalec -  - Courses: 0 - Projects: 0
Aleš Erjavec - Tehniški sodelavec - T: +386 1 479 8209 - Courses: 0 - Projects: 5
doc. dr. Jana Faganeli Pucer - Asistent - T: +386 1 479 8226 - Courses: 3 - Projects: 7
asist. dr. Gašper Fele Žorž - Računalniški center - T: +386 1 479 8221 - Courses: 3 - Projects: 3
prof. dr. Gašper Fijavž - Redni profesor - T: +386 1 479 8201 - Courses: 4 - Projects: 0
Marko Firm - Vzdrževalec -  - Courses: 0 - Projects: 0
Borut Flis - Tehniški sodelavec -  - Courses: 0 - Projects: 0
asist. dr. Aleksandra Franc - Asistent - T: +386 1 479 8258 - Courses: 5 - Projects: 1
asist. dr. Damir Franetič - Asistent - T: +386 1 479 8258 - Courses: 6 - Projects: 1
asist. asist. Matic Fučka - Raziskovalec -  - Courses: 0 - Projects: 0
asist. dr. Damjan Fujs - Asistent - T: +386 1 4798 261 - Courses: 4 - Projects: 2
Svetlana Fuks - Raziskovalec -  - Courses: 0 - Projects: 0
Erika Funa - Drugi člani -  - Courses: 0 - Projects: 1
doc. dr. Luka Fürst - Asistent - T: +386 1 479 8213 - Courses: 4 - Projects: 3
Gregor Gabrovšek - Tehniški sodelavec -  - Courses: 0 - Projects: 1
asist. asist. Peter Gabrovšek - Asistent -  - Courses: 2 - Projects: 0
Timotej Gale - Tehniški sodelavec -  - Courses: 0 - Projects: 0
Kaja Gantar - Raziskovalec -  - Courses: 0 - Projects: 0
znan. sod. dr. Apolonija Gantar - Drugi člani -  - Courses: 0 - Projects: 0
Bruno Gašperov - Drugi člani -  - Courses: 0 - Projects: 0
asist. dr. Sandi Gec - Asistent - Govorilne ure: Četetek, 10:00–11:00 (ali po dogovoru) - Courses: 2 - Projects: 6
doc. dr. Dejan Georgiev - Drugi člani -  - Courses: 0 - Projects: 1
Atiyeh Ghane - Raziskovalec -  - Courses: 0 - Projects: 0
Martin Gjoreski - Drugi člani -  - Courses: 0 - Projects: 0
asist. Primož Godec - Zunanji sodelavec -  - Courses: 0 - Projects: 0
Saša Gojić - Služba za komuniciranje - T: 014798110 - Courses: 0 - Projects: 0
asist. asist. Rok Gomišček - Asistent - T: +386 1 479 8209 - Courses: 3 - Projects: 0
asist. asist. Peter Goričan - Asistent -  - Courses: 3 - Projects: 0
Vesna Gračner - Mednarodna pisarna - T: +386 1 479 8249 - Courses: 0 - Projects: 0
Andrej Grebenc - Raziskovalec -  - Courses: 0 - Projects: 0
Rok Gregorin - Dekanat -  - Courses: 0 - Projects: 0
asist. asist. Miha Grohar - Asistent - T: +386 1 479 8205 - Courses: 2 - Projects: 11
doc. dr. Vida Groznik - Asistent - T: +386 1 479 8252 - Courses: 2 - Projects: 4
Zala Gruden - Zunanji sodelavec -  - Courses: 0 - Projects: 0
doc. dr. Matej Guid - Asistent - T: +386 1 479 8278 - Courses: 5 - Projects: 4
asist. asist. Ana Halužan Vasle - Asistent -  - Courses: 2 - Projects: 0
doc. dr. Tomaž Hočevar - Asistent - T: +386 1 479 8209 - Courses: 4 - Projects: 6
prof. dr. Tomaž Hovelja - Redni profesor - T: +386 1 479 8265 - Courses: 2 - Projects: 8
asist. dr. Aleks Huč - Asistent - T: +386 1 479 8243 - Courses: 4 - Projects: 5
Kama Hudobivnik - Finančno-računovodska služba - T: +386 1 479 8125 - Courses: 0 - Projects: 0
Ana Hvastija - Dekanat - T: +386 1 479 8100 - Courses: 0 - Projects: 0
Leon Hvastja - Tehniški sodelavec -  - Courses: 0 - Projects: 0
doc. dr. Nejc Ilc - Zunanji sodelavec - T: +386 1 479 8231 - Courses: 0 - Projects: 4
prof. dr. Franc Jager - Redni profesor - T: +386 1 479 8270 - Courses: 2 - Projects: 3
doc. dr. Aleš Jaklič - Asistent - T: +386 1 479 8240 - Courses: 4 - Projects: 8
asist. dr. Miha Janež - Asistent -  - Courses: 5 - Projects: 4
dr. Stefana Janičijević - Asistent -  - Courses: 0 - Projects: 0
viš. pred. dr. David Jelenc - Asistent - T: +386 1 479 8243 - Courses: 4 - Projects: 12
Gašper Jelovčan - Raziskovalec -  - Courses: 0 - Projects: 0
asist. dr. Gregor Jerše - Drugi člani - T: +386 1 479 8258 - Courses: 0 - Projects: 0
prof. dr. Branko Matjaž Jurič - Redni profesor - T: +386 1 479 8275 - Courses: 2 - Projects: 23
prof. dr. Aleksandar Jurišić - Redni profesor - Govorilne ure: torek 15:00-16:00 (prosim za najavo po e-pošti) - Courses: 3 - Projects: 6
Arvin Jušić - Tehniški sodelavec -  - Courses: 0 - Projects: 0
Andraž Juvan - Tehniški sodelavec -  - Courses: 3 - Projects: 0
Jure Juvan - Tehniški sodelavec -  - Courses: 0 - Projects: 0
doc. dr. Tadej Kanduč - Docent -  - Courses: 3 - Projects: 0
Aneta Kartali - Mladi raziskovalec -  - Courses: 0 - Projects: 0
doc. dr. Alenka Kavčič - Asistent - T: +386 1 479 8259 - Courses: 4 - Projects: 15
prof. dr. Borut Paul Kerševan - Zunanji sodelavec -  - Courses: 1 - Projects: 0
asist. dr. Peter Marijan Kink - Asistent - T: +386 1 479 8258 - Courses: 6 - Projects: 2
Klavdija Kitek - Služba za raziskovalno dejavnost -  - Courses: 0 - Projects: 0
asist. asist. Klemen Klanjšček - Asistent -  - Courses: 3 - Projects: 0
asist. asist. Matej Klemen - Mladi raziskovalec -  - Courses: 0 - Projects: 1
pred. mag. Bojan Klemenc - Asistent - T: +386 1 479 8240 - Courses: 3 - Projects: 2
Vid Klopčič - Tehniški sodelavec -  - Courses: 0 - Projects: 1
Timotej Knez - Mladi raziskovalec -  - Courses: 2 - Projects: 0
doc. dr. Petar Kochovski - Asistent - Govorilne ure: Po dogovoru - Courses: 4 - Projects: 10
asist. asist. Jaka Kokošar - Mladi raziskovalec -  - Courses: 1 - Projects: 0
Boshko Koloski - Drugi člani -  - Courses: 1 - Projects: 0
prof. dr. Igor Kononenko - Raziskovalec - T: +386 1 479 8230 - Courses: 0 - Projects: 11
Miran Koprivec - Tehniški sodelavec - T: +386 1 479 8204 - Courses: 3 - Projects: 0
Sara Kos - Drugi člani -  - Courses: 0 - Projects: 0
dr. Iztok Kosem - Drugi člani -  - Courses: 0 - Projects: 0
asist. dr. Domen Košir - Zunanji sodelavec - T: +386 1 479 8226 - Courses: 0 - Projects: 0
doc. dr. Simon Krek - Drugi člani -  - Courses: 0 - Projects: 0
prof. dr. Matej Kristan - Redni profesor - T: +386 1 479 8225 - Courses: 7 - Projects: 13
asist. asist. Yannick Kuhar - Mladi raziskovalec -  - Courses: 0 - Projects: 0
izr. prof. dr. Matjaž Kukar - Izredni profesor - T: +386 1 479 8235 - Courses: 3 - Projects: 17
asist. asist. Romanela Lajić - Asistent -  - Courses: 2 - Projects: 0
asist. asist. Ajda Lampe - Asistent - Govorilne ure: po dogovoru - Courses: 1 - Projects: 2
asist. dr. Leon Lampret - Asistent -  - Courses: 0 - Projects: 0
pred. mag. Iztok Lapanja - Zunanji sodelavec -  - Courses: 0 - Projects: 0
Nicolas Larue - Drugi člani -  - Courses: 0 - Projects: 0
asist.-raz. dr. Cyprian Adam Laskowski - Asistent -  - Courses: 0 - Projects: 0
izr. prof. dr. Dejan Lavbič - Izredni profesor - T: +386 1 479 8233 - Courses: 3 - Projects: 13
asist. dr. Timotej Lazar - Računalniški center - T: +386 1 479 8277 - Courses: 1 - Projects: 3
izr. prof. dr. Iztok Lebar Bajec - Izredni profesor - T: +386 1 479 8217 - Courses: 2 - Projects: 10
prof. dr. Aleš Leonardis - Redni profesor - Govorilne ure: Ponedeljek od 15.00-16.00 - Courses: 0 - Projects: 11
asist. asist. Žiga Lesar - Asistent -  - Courses: 3 - Projects: 2
doc. dr. Jure Leskovec - Drugi člani -  - Courses: 2 - Projects: 0
André Lezan Fernandes - Zunanji sodelavec -  - Courses: 0 - Projects: 0
doc. dr. Nikola Ljubešić - Drugi člani -  - Courses: 0 - Projects: 1
Sonja Lojk - Dekanat - T: +386 1 479 8011 - Courses: 0 - Projects: 0
mag. Matija Lokar - Drugi člani -  - Courses: 0 - Projects: 1
prof. dr. Uroš Lotrič - Redni profesor - T: +386 1 479 8298 - Courses: 4 - Projects: 11
doc. dr. Alan Lukežič - Asistent - T: +386 1 479 8245 - Courses: 1 - Projects: 0
Aleksandra Lutar Ivanc - Služba za raziskovalno dejavnost -  - Courses: 0 - Projects: 0
Luka Maček - Tehniški sodelavec -  - Courses: 0 - Projects: 0
Nives Macerl - Tajništvo
Tajnik fakultete - T: +386 1 479 8113 - Courses: 0 - Projects: 0
asist. dr. Alina - Luminita Machidon - Asistent -  - Courses: 0 - Projects: 4
doc. dr. Octavian Mihai Machidon - Asistent -  - Courses: 3 - Projects: 4
Marta Malavolta - Raziskovalec -  - Courses: 0 - Projects: 0
Miha Malenšek - Raziskovalec -  - Courses: 0 - Projects: 0
Mateja Malešič - Kadrovska služba - T: +386 1 479 8114 - Courses: 0 - Projects: 0
mag. Luka Mali - Raziskovalec -  - Courses: 1 - Projects: 0
asist. asist. Mila Marinković - Raziskovalec -  - Courses: 3 - Projects: 0
Jernej Markelj - Asistent -  - Courses: 0 - Projects: 1
prof. dr. Matija Marolt - Redni profesor - T: +386 1 479 8259 - Courses: 7 - Projects: 20
Teodora Matić - Raziskovalec -  - Courses: 0 - Projects: 1
Mateja Mavrič - Drugi člani -  - Courses: 0 - Projects: 0
asist. dr. Blaž Meden - Asistent -  - Courses: 3 - Projects: 5
asist. dr. Daša Mesarič Štesl - Asistent -  - Courses: 3 - Projects: 0
as. Jan Meznarič - Zunanji sodelavec - Govorilne ure: Po dogovoru. - Courses: 0 - Projects: 0
Nataša Mihalič - Finančno-računovodska služba -  - Courses: 0 - Projects: 0
Anže Mihelič - Raziskovalec -  - Courses: 0 - Projects: 0
izr. prof. dr. Jurij Mihelič - Izredni profesor - T: +386 1 479 8236 - Courses: 3 - Projects: 12
Vanja Mileski - Raziskovalec -  - Courses: 0 - Projects: 0
asist. asist. Pouriya Miri - Mladi raziskovalec - Govorilne ure: Ponedeljek - Petek: 14:00 - 16:00 (samo za produktiven dialog) - Courses: 0 - Projects: 0
Teodora Mishevska Kochovski - Raziskovalec -  - Courses: 0 - Projects: 1
doc. dr. David Modic - Docent - T: 014798251 - Courses: 6 - Projects: 1
izr. prof. dr. Miha Moškon - Izredni profesor
Prodekan - T: +386 1 479 8217 - Courses: 4 - Projects: 12
doc. dr. Martin Možina - Asistent - T: +386 1 479 8210 - Courses: 1 - Projects: 10
prof. dr. Nežka Mramor Kosta - Upokojeni profesor - T: +386 1 479 8242 - Courses: 0 - Projects: 3
prof. dr. Miha Mraz - Redni profesor - T: +386 1 479 8215 - Courses: 6 - Projects: 11
asist. asist. Jon Natanael Muhovič - Asistent -  - Courses: 3 - Projects: 5
asist. asist. David Nabergoj - Mladi raziskovalec -  - Courses: 1 - Projects: 0
Mimoza Naseka - Drugi člani -  - Courses: 0 - Projects: 0
Andreja Nič - Zunanji sodelavec -  - Courses: 0 - Projects: 0
Jakob Novak - Drugi člani -  - Courses: 0 - Projects: 0
izr. prof. dr. Polona Oblak - Izredni profesor - T: +386 1 479 8264 - Courses: 6 - Projects: 10
asist. asist. Tim Oblak - Asistent -  - Courses: 2 - Projects: 1
pred. pred. Saša Ogrizović - Predavatelj -  - Courses: 5 - Projects: 0
prof. dr. Bojan Orel - Upokojeni profesor - T: +386 1 479 8283 - Courses: 0 - Projects: 0
Neža Pajek Arambašič - Raziskovalec -  - Courses: 0 - Projects: 2
pred. dr. Matjaž Pančur - Asistent - T: +386 1 479 8205 - Courses: 4 - Projects: 15
prof. dr. Petar Pavešić - Raziskovalec -  - Courses: 0 - Projects: 0
prof. dr. Peter Peer - Redni profesor - T: +386 1 479 8248 - Courses: 4 - Projects: 18
izr. prof. dr. Veljko Pejović - Izredni profesor - T: +386 1 479 8257 - Courses: 3 - Projects: 9
asist. asist. Jer Pelhan - Asistent -  - Courses: 2 - Projects: 0
doc. dr. Matevž Pesek - Docent - T: +386 1 479 8259 - Courses: 5 - Projects: 16
asist. asist. Bernarda Petek - Mladi raziskovalec -  - Courses: 1 - Projects: 0
dr. Andrej Petelin - Zunanji sodelavec -  - Courses: 0 - Projects: 0
asist. dr. Matej Pičulin - Asistent - T: +386 1 479 8226 - Courses: 3 - Projects: 3
doc. dr. Ratko Pilipović - Asistent -  - Courses: 3 - Projects: 4
asist. asist. Žiga Pirnar - Asistent -  - Courses: 1 - Projects: 1
asist. asist. Teodor Janez Podobnik - Raziskovalec -  - Courses: 0 - Projects: 0
dr. Vid Podpečan - Zunanji sodelavec -  - Courses: 0 - Projects: 0
Gaber Polajnar - Raziskovalec -  - Courses: 0 - Projects: 0
asist. asist. Pavlin Gregor Poličar - Asistent -  - Courses: 2 - Projects: 0
doc. dr. Senja Pollak - Zunanji sodelavec -  - Courses: 0 - Projects: 0
doc. dr. Damjan Popič - Drugi člani -  - Courses: 0 - Projects: 0
dr. Aleš Popovič - Raziskovalec -  - Courses: 0 - Projects: 0
asist. dr. Eva Pori - Asistent -  - Courses: 0 - Projects: 0
Mitja Potočar - Tehniški sodelavec -  - Courses: 0 - Projects: 0
asist. dr. Marko Poženel - Asistent - T: +386 1 479 8213 - Courses: 4 - Projects: 1
Ela Praznik - Raziskovalec -  - Courses: 0 - Projects: 0
asist.-raz. dr. Ajda Pretnar Žagar - Asistent - T: +386 1 479 8209 - Courses: 0 - Projects: 8
asist. asist. Žiga Pušnik - Asistent -  - Courses: 3 - Projects: 2
Mihael Rajh - Raziskovalec -  - Courses: 0 - Projects: 0
Vid Rijavec - Tehniški sodelavec -  - Courses: 2 - Projects: 0
Mitja Rizvič - Raziskovalec -  - Courses: 0 - Projects: 1
prof. dr. Borut Robič - Redni profesor - T: +386 1 479 8250 - Courses: 4 - Projects: 6
Nejc Robida - Raziskovalec -  - Courses: 0 - Projects: 1
Rebeka Roblek - Drugi člani -  - Courses: 0 - Projects: 0
prof. dr. Marko Robnik Šikonja - Redni profesor - T: +386 1 479 8241 - Courses: 7 - Projects: 24
asist. asist. Blaž Rolih - Mladi raziskovalec -  - Courses: 0 - Projects: 0
asist. asist. Peter Rot - Raziskovalec -  - Courses: 0 - Projects: 3
viš. pred. dr. Igor Rožanc - Asistent - T: +386 1 479 8202 - Courses: 3 - Projects: 0
strok. sod. mag. Ksenija Rozman - Tajništvo - T: +386 1 479 8282 - Courses: 1 - Projects: 0
viš. pred. dr. Robert Rozman - Asistent - T: +386 1 479 8202 - Courses: 3 - Projects: 1
Taja Runovc - Študentski referat - T: +386 1 479 8121 - Courses: 0 - Projects: 0
doc. dr. Rok Rupnik - Docent - T: +386 1 479 8266 - Courses: 3 - Projects: 3
asist. asist. Marko Rus - Raziskovalec -  - Courses: 0 - Projects: 0
izr. prof. dr. Aleksander Sadikov - Izredni profesor - T: +386 1 479 8210 - Courses: 4 - Projects: 16
Miha Schaffer - Računalniški center - T: +386 1 479 8222 - Courses: 0 - Projects: 0
Qomri Sholeh - Raziskovalec -  - Courses: 0 - Projects: 0
Petra Simonič - Knjižnica - T: +386 1 479 8005 - Courses: 0 - Projects: 0
prof. dr. Danijel Skočaj - Redni profesor - T: +386 1 479 8225 - Courses: 8 - Projects: 25
Jasmina Slapničar - Služba za raziskovalno dejavnost -  - Courses: 0 - Projects: 0
Tadej Slemenšek - Tehniški sodelavec -  - Courses: 0 - Projects: 0
doc. dr. Boštjan Slivnik - Docent - T: +386 1 479 8203 - Courses: 3 - Projects: 10
asist. dr. Davor Sluga - Asistent - T: +386 1 479 8231 - Courses: 4 - Projects: 11
Aleš Smonig Grnjak - Študentski referat - T: +386 1 479 8119 - Courses: 0 - Projects: 0
doc. dr. Aleš Smrdel - Asistent - T: +386 1 479 8211 - Courses: 2 - Projects: 1
prof. dr. Franc Solina - Redni profesor - T: +386 1 479 8246 - Courses: 6 - Projects: 13
prof. dr. Vlado Stankovski - Redni profesor
Prodekan - T: 01 4798 285 - Courses: 3 - Projects: 11
asist. asist. Lidija Stanovnik - Mladi raziskovalec -  - Courses: 1 - Projects: 3
doc. dr. Mojca Svetek - Drugi člani -  - Courses: 0 - Projects: 0
doc. dr. Luka Šajn - Asistent - T: +386 1 479 8220 - Courses: 5 - Projects: 3
Josip Šarić - Drugi člani -  - Courses: 0 - Projects: 0
Meta Šeruga - Dekanat -  - Courses: 0 - Projects: 0
Andrej Šeruga - Vzdrževalec - T: +386 41 304 741 - Courses: 0 - Projects: 0
Iztok Škof - Raziskovalec -  - Courses: 0 - Projects: 1
asist. asist. Blaž Škrlj - Zunanji sodelavec -  - Courses: 0 - Projects: 0
asist. dr. Tadej Škvorc - Asistent -  - Courses: 3 - Projects: 1
asist. asist. Uroš Šmajdek - Mladi raziskovalec -  - Courses: 1 - Projects: 0
asist. dr. Domen Šoberl - Asistent - T: +386 1 479 8210 - Courses: 1 - Projects: 0
Tjaša Šoltes - Raziskovalec -  - Courses: 0 - Projects: 0
asist. asist. Martin Špendl - Mladi raziskovalec -  - Courses: 2 - Projects: 0
Maja Špolad - Služba za raziskovalno dejavnost -  - Courses: 0 - Projects: 0
prof. dr. Branko Šter - Redni profesor - T: +386 1 479 8247 - Courses: 3 - Projects: 6
prof. dr. Erik Štrumbelj - Raziskovalec - T: +386 1 479 8235 - Courses: 3 - Projects: 16
izr. prof. dr. Lovro Šubelj - Izredni profesor - T: +386 1 479 8233 - Courses: 3 - Projects: 5
znan. sod. dr. Domen Tabernik - Drugi člani - T: +386 1 479 8245 - Courses: 0 - Projects: 10
as. asist. Vesna Tanko - Raziskovalec -  - Courses: 0 - Projects: 3
asist. asist. Luka Terčon - Raziskovalec -  - Courses: 0 - Projects: 1
asist. asist. Darian Tomašević - Mladi raziskovalec -  - Courses: 0 - Projects: 0
asist. dr. Marko Toplak - Asistent - T: +386 1 479 8209 - Courses: 2 - Projects: 19
Barbara Torkar - Knjižnica -  - Courses: 0 - Projects: 0
prof. dr. Denis Trček - Redni profesor - T: +386 1 479 8269 - Courses: 7 - Projects: 23
izr. prof. dr. Mira Trebar - Upokojeni profesor - T: +386 1 479 8254 - Courses: 0 - Projects: 0
mag. Jernej Trnkoczy - Raziskovalec -  - Courses: 0 - Projects: 0
Klemen Turkovič - Tehniški sodelavec -  - Courses: 0 - Projects: 0
as.- raz. dr. Jure Tuta - Zunanji sodelavec -  - Courses: 1 - Projects: 0
prof. dr. Damjan Vavpotič - Redni profesor
Prodekan - T: +386 1 479 8228 - Courses: 4 - Projects: 9
Zdenka Velikonja - Študentski referat - T: +386 1 479 8123 - Courses: 0 - Projects: 0
asist. dr. Kristina Veljković - Asistent -  - Courses: 2 - Projects: 1
asist. dr. Melanija Vezočnik - Asistent -  - Courses: 3 - Projects: 1
doc. dr. Janoš Vidali - Zunanji sodelavec - T: +386 1 479 8271 - Courses: 0 - Projects: 0
Urša Vidic - Zunanji sodelavec -  - Courses: 0 - Projects: 0
Martin Vidmar - Tehniški sodelavec -  - Courses: 0 - Projects: 0
izr. prof. dr. Žiga Virk - Izredni profesor - T: +386 1 479 8244 - Courses: 4 - Projects: 4
asist. asist. Matej Vitek - Asistent - Govorilne ure: Ponedeljek 17-18h - Courses: 2 - Projects: 4
Jaka Vodeb - Zunanji sodelavec -  - Courses: 0 - Projects: 0
prof. dr. Irena von Arx Ograjenšek - Raziskovalec -  - Courses: 0 - Projects: 0
doc. dr. Petar Vračar - Asistent - T: +386 1 479 8226 - Courses: 1 - Projects: 10
Domen Vreš - Raziskovalec -  - Courses: 0 - Projects: 2
Simon Vrhovec - Zunanji sodelavec - T: +386 1 4768 198 - Courses: 1 - Projects: 0
asist. dr. Martin Vuk - Asistent - T: +386 1 479 8258 - Courses: 3 - Projects: 5
Aleš Watzak - Računalniški center - T: +386 1 479 8223 - Courses: 0 - Projects: 0
doc. dr. Aljaž Zalar - Docent -  - Courses: 5 - Projects: 2

In [77]:
df

,Name,Title,Number,Number of courses,Number of projects
0,Marija Absec,Tehniški sodelavec,,0,0
1,dr. Areeb Ahmed,Drugi člani,,0,0
2,Špela Antloga,Raziskovalec,,0,0
3,Tjaša Arčon,Raziskovalec,,0,0
4,znan. sod. dr. Špela Arhar Holdt,Drugi člani,,0,4
...,...,...,...,...,...
288,izr. prof. dr. Slavko Žitnik,Izredni profesor\nProdekan,T: +386 1 476 82 16,13,15
289,Urška Žnidarič,Drugi člani,T: +386 1 4798111,0,0
290,Klara Žnideršič,Tehniški sodelavec,,0,1
291,doc. dr. Bojan Žunkovič,Asistent,,6,1
292,asist. asist. Lojze Žust,Asistent,,1,1

In [78]:
df.to_csv('data/professors_data.csv', index=False)

In [79]:
driver.quit()

In [62]:
for url in profile_urls[7:9]:
    driver.get(url)
    time.sleep(5)
    
    num_courses = 0
    headers = driver.find_elements(By.CLASS_NAME, "aboutMainSectionContainer")
    for header in headers:
        # print(header.text)
        if "PREDMETI" in header.text:
            courses_div = header.find_element(By.CLASS_NAME, "aboutMainSectionLi")
            courses_list = courses_div.find_element(By.TAG_NAME, "ul")
            course_items = courses_list.find_elements(By.TAG_NAME, "li")
            num_courses = len(course_items)
            break
    # 
    # print(f"Number of courses: {num_courses}")
 
    # # Counting projects under "Projekti" and "Zakljuceni projekti"
    num_active_projects = 0
    num_completed_projects = 0
    for header in headers:
        if "PROJEKTI" in header.text:
            projects_div = header.find_element(By.CLASS_NAME, "aboutMainSectionLi")
            projects_list = projects_div.find_elements(By.TAG_NAME, "ul")
            # print(projects_list)
            project_items = projects_list[0].find_elements(By.TAG_NAME, "li")
            num_active_projects = len(project_items)
            completed_project_items = projects_list[1].find_elements(By.TAG_NAME, "li")
            num_completed_projects = len(completed_project_items)
        # elif "Zaključeni projekti" in header.text:
        #     completed_projects_list = header.find_element(By.XPATH, "../following-sibling::ul[@class='customList']")
        #     completed_project_items = completed_projects_list.find_elements(By.TAG_NAME, "li")
        #     num_completed_projects = len(completed_project_items)

    total_projects = num_active_projects + num_completed_projects
    
    # Save data for each professor (you can also print or log it here)
    print(f"Courses: {num_courses}, Active Projects: {num_active_projects}, Completed Projects: {num_completed_projects}, Total Projects: {total_projects}")

Courses: 3, Active Projects: 4, Completed Projects: 33, Total Projects: 37
Courses: 3, Active Projects: 2, Completed Projects: 6, Total Projects: 8